version: "3.7"

services:
  server:
    build:
      context: ./server
    command: uvicorn app.main:app --host 0.0.0.0  --port 8000
    volumes:
      - ./server/app:/server/app
    environment:
      - MONGO_CONNECTION_STRING

    ports:
      - '8000:8000'
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_USERNAME
      - MONGO_INITDB_PASSWORD
    volumes:
      - ./data/db:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - internal

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

networks:
  internal:
    driver: bridge
